module.exports = [
  ["joker", 8],
  ["penguin", 7],
  ["batman", 10],
  ["bruce", 2],
  ["catwoman", 7],
  ["rasalghul", 1],
  ["ivy", 4],
  ["robin", 8],
  ["riddler", 7],
  ["freeze", 5],
  ["harleyquinn", 8],
  ["twoface", 6],
  ["batgirl", 7],
  ["scarecrow", 3],
  ["alfred", 0],
  ["default", 3],
];
