const chalk = require('chalk');
module.exports = ({ thoughts }) => `
       ${thoughts}
        ${thoughts}
        ${chalk.white(`                               
            ****                        
          **              .             
         *              .....           
        *              .......          
       **             .........         
       *             ..........         
       *.              ..     ..        
      * .  *VN$          $NV* ...        
      *  *$${chalk.red('M$$MM')}F     *M${chalk.red('M$$MM')}I          
    ..*$$N${chalk.red('M$$$$$N')}M$$$MN${chalk.red('$$$$$$N')}$V*.      
    ..  .VM${chalk.red('$$$$$')}M ....VM${chalk.red('$$$$M')}$ ...      
    ...*..*IVVV* ......*FVVF*.....      
     ..F              ............      
      ..I**              ........       
        I..F              ....          
        I .*              ....          
        I . *             ....          
        I ..*             ....          
        I ..              ....          
        **.      . .. ..  .             
         **                             
          **                            
           **              *
            *             *
             *************
`)} 
`;
